import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <Link href={"/"}>
              <li>Home</li>
            </Link>
            <Link href={"/list"}>
              <li>글목록</li>
            </Link>
            <Link href={"/write"}>
              <li>글쓰기</li>
            </Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
